github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: ${GITHUB_REDIRECT_URI}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${AWS_S3_BUCKET}

amazon:
  pa:
    access-key: ${AMAZON_PA_ACCESS_KEY}
    secret-key: ${AMAZON_PA_SECRET_KEY}
    partner-tag: ${AMAZON_PA_PARTNER_TAG}
    region: ${AMAZON_PA_REGION:us-east-1}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

logging:
  level:
    com.pointsmall: WARN
